export const COMPANY = [
  { value: 'kakao', label:'카카오' },
  { value: 'community', label:'공동체' },
]

export const CATEGORY = {
  kakao: [
    { value: 'platform', label: '플랫폼부문' },
    { value: 'ai_lap', label: 'AI Lab' },
    { value: 'service', label: '서비스부문' },
    { value: 'contents', label: '콘텐츠부문' },
    { value: 'biz', label: '바즈파트너부문' },
    { value: 'infra', label: '인프라플랫폼실' },
    { value: 'etc', label: '기타 서비스' },
    { value: 'multi', label: '멀티 서비스' },
    { value: 'in_house', label: '사내 시스템' },
  ],
  community: [
    { value: 'podotree', label: '포토트리' },
    { value: 'path_mobile', label: 'path mobile' },
    { value: 'kids_note', label: '키즈노트' },
    { value: 'kakao_games', label: '카카오 게임즈' },
    { value: 'kakao_friends', label: '카카오 프렌즈' },
    { value: 'kakao_bank', label: '카카오뱅크' },
    { value: 'kakao_makers', label: '카카오메이커스' },
    { value: 'kakao_pay', label: '카카오 페이' },
    { value: 'kakao_mobility', label: '카카오모빌리티' },
    { value: 'kakao_hair', label: '카카오헤어' },
    { value: 'kakao_m', label: '카카오M' },
    { value: 'dk_ocg', label: 'DK OCG' },
    { value: 'etc', label: '기타계열사' },
    { value: 'external', label: '외부사업' },
  ]
}

export const SERVICE = {
  kakao: {
    platform: [
      { value: 'common', label: '공통' },
      { value: 'yellow_id', label: '옐로아이디' },
      { value: 'open_chat', label: '오픈채팅' },
      { value: 'sharp_search', label: '샵검색' },
      { value: 'emoticon', label: '이모티콘' },
      { value: 'plus_friend', label: '플러스친구' },
      { value: 'kakao_order', label: '카카오주문하기' },
      { value: 'channel_tab', label: '채널탭' },
      { value: 'kakao_story', label: '카카오스토리' },
      { value: 'account', label: '회원정보, 계정' },
      { value: 'cheese', label: '치즈' },
    ],
    ai_lap: [
      { value: 'common', label: '공통' },
      { value: 'search', label: '검색' },
      { value: 'search_admin', label: '검색운영툴' },
      { value: 'multimedia', label: '멀티미디어' },
      { value: 'encyclopedia', label: '백과사전' },
      { value: 'dictionary', label: '어학사전' },
      { value: 'etc', label: '기타' },
    ],
    service: [
      { value: 'common', label: '공통' },
      { value: 'pc_top', label: 'PC TOP' },
      { value: 'daum_app', label: '다음앱' },
      { value: 'mail', label: '메일' },
      { value: 'cafe', label: '카페' },
      { value: 'fun', label: 'FUN' },
      { value: 'daum_blog', label: '다음블로그' },
      { value: 'brunch', label: '브런치' },
      { value: 'tistory', label: '티스토리' },
      { value: 'movie', label: '영화' },
      { value: 'news', label: '뉴스' },
      { value: 'sports', label: '스포츠' },
      { value: 'entertainments', label: '연예' },
      { value: 'car', label: '자동차' },
      { value: 'life', label: '라이프' },
      { value: '1boon', label: '1boon' },
      { value: 'story_fund', label: '스토리펀딩' },
      { value: 'cooking', label: '요리' },
      { value: 'miznet', label: '미즈넷' },
      { value: 'agora', label: '아고라' },
      { value: 'book', label: '책' },
      { value: 'channel', label: '채널' },
      { value: 'tip', label: '팁' },
    ],
    contents: [
      { value: 'common', label: '공통' },
      { value: 'kakao_tv', label: 'tv팟/카카오TV' },
      { value: 'real_estate', label: '부동산' },
      { value: 'finance', label: '금융' },
    ],
    biz: [
      { value: 'common', label: '공통' },
      { value: 'kakao_tv', label: '중계광고' },
      { value: 'real_estate', label: '쇼핑광고' },
      { value: 'search_ad', label: '검색광고' },
      { value: 'network_ad', label: '네트워크광고' },
      { value: 'kakao_story_ad', label: '카카오스토리광고' },
      { value: 'display_ad', label: '디스플레이광고' },
      { value: 'local_ad', label: '로컬광고' },
      { value: 'shopping_how', label: '쇼핑하우/핫딜' },
      { value: 'kakao_style', label: '카카오스타일' },
      { value: 'kakao_shopping', label: '카카오쇼핑' },
      { value: 'gift', label: '선물하기' },
      { value: 'kakao_market', label: '카카오장보기' },
      { value: 'winterfell', label: '윈터펠' },
      { value: 'kakao_farmer', label: '카카오파머' },
    ],
    infra: [
      { value: 'common', label: '공통' },
      { value: 'traffic', label: '교통' },
      { value: 'place', label: '장소' },
      { value: 'map', label: '지도' },
      { value: 'kakao_map', label: '카카오맵' },
      { value: 'kakao_subway', label: '카카오지하철' },
      { value: 'kakao_bus', label: '카카오버스' },
      { value: 'agit', label: '아지트' },
      { value: 'web_component', label: 'Web Component' },
      { value: 'daum_editor', label: '다음 에디터' },
      { value: 'billing', label: '빌링' },
      { value: 'infra', label: '인프라' },
      { value: 'etc', label: '기타' },
    ],
    etc: [
      { value: 'kakao_place', label: '카카오플레이스' },
      { value: 'kakao_music', label: '카카오뮤직' },
      { value: 'social_welfare', label: '같이가치' },
      { value: 'daum_cleaner', label: '다음 클리너' },
      { value: 'privacy', label: '개인정보' },
      { value: 'service_center', label: '고객센터' },
      { value: 'company_site', label: '기업사이트' },
      { value: 'brand_site', label: '브랜드사이트' },
      { value: 'affiliate_site', label: '제휴사이트' },
      { value: 'kakao_people', label: '카카오피플' },
      { value: 'survey_system', label: '설문시스템' },
      { value: 'etc', label: '기타' },
    ],
    multi: [
      { value: 'un_title', label: '-' },
    ],
    in_house: [
      { value: 'in_house', label: '사내 시스템' },
    ]
  },
  community: {
    podotree: [
      { value: 'webtoon', label: '웹툰' },
      { value: 'kakao_page', label: '카카오페이지' },
    ],
    path_mobile: [
      { value: 'un_title', label: '-' },
    ],
    kids_note: [
      { value: 'kids_note', label: '키즈노트 서비스' },
      { value: 'one_homepage', label: '원 홈페이지' },
    ],
    kakao_games:[
      { value: 'daum_game', label: '다음게임' },
      { value: 'kakao_game', label: '카카오게임' },
      { value: 'etc', label: '기타' },
    ],
    kakao_friends: [
      { value: 'online_store', label: '온라인스토어' },
      { value: 'museum', label: '뮤지엄' },
      { value: 'licensee', label: '라이센사' },
    ],
    kakao_bank: [
      { value: 'un_title', label: '-' },
    ],
    kakao_makers: [
      { value: 'un_title', label: '-' },
    ],
    kakao_pay: [
      { value: 'common', label: '공통' },
      { value: 'tax', label: '공과금' },
      { value: 'membership', label: '멤버쉽' },
      { value: 'bill', label: '청구서' },
      { value: 'kakao_money', label: '카카오머니' },
      { value: 'kakao_pay', label: '카카오페이' },
      { value: 'promotion', label: '프로모션' },
      { value: 'customer_center', label: '고객센터' },
    ],
    kakao_mobility: [
      { value: 'common', label: '공통' },
      { value: 'kakao_t', label: '카카오T' },
      { value: 'kakao_driver', label: '카카오드라이버' },
      { value: 'kakao_parking', label: '카카오파킹' },
      { value: 'kakao_navigation', label: '카카오내비' },
    ],
    kakao_hair: [
      { value: 'kakao_salon', label: '카카오헤어샵' },
    ],
    kakao_m: [
      { value: 'common', label: '공통' },
      { value: 'company_site', label: '기업사이트' },
      { value: 'infra', label: '인프라' },
    ],
    dk_ocg: [
      { value: 'in_house_system', label: '사내 정보 시스템' },
      { value: 'report_system', label: '업무 리포트 시스템' },
    ],
    etc: [
      { value: 'image_on', label: '이미지온' },
      { value: 'linkage_lab', label: '링키지랩' },
    ],
    external: [
      { value: 'i_producer', label: 'i-produce' },
      { value: 'new_world', label: '신세계' },
    ],
  }
}